#!/bin/bash
run_rc() {
    echo "Running '$1'"
    $1
}
run_rc 'inspekt lint --exclude .venv'
rc1=$?
echo ""
run_rc 'inspekt indent --exclude .venv'
rc2=$?
echo ""
run_rc 'inspekt style --exclude .venv'
rc3=$?
exit $rc1 || $rc2 || $rc3

